import "./globals.css";
import "./style.css";
import Header from "./components/header";
export const metadata = {
  title: "Moteur&Sens Location",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <>
      <html lang="en">
        <body className="px-2">
          <Header />
          <div>{children}</div>
        </body>
      </html>
    </>
  );
}
